export const LoadmapData = [
    {
        title: 'January 2022 - March 2022',
        image: '3',
        mt: '0',
        bridge: 'bridge_1.png',
        header: 'The Build-Up',
        body: 'The first phase of the Planet of Cyborgs  project is to build our community, through various marketing strategies as well as active engagement within the community across our social platforms incentivised by competitions, giveaways, games, collaborations and more.'
    },
    {
        title: 'March 2022',
        image: '6',
        mt: '0',
        bridge: 'bridge_2.png',
        header: 'The Build-Up',
        body: '3,022 unique Cyborgs will be minted through our website. Whitelisted users can gain access to the project before the general public. Each Cyborg is generated by code to make all the variations, with 200+ unique traits such as Head and Torso Systems, Eyes, Mouth and Shoulder Subsystems and more!'
    },
    {
        title: '2022',
        image: '7',
        mt: '0',
        bridge: 'bridge_1.png',
        header: 'Planet of Cyborgs Merch',
        body: 'Following the minting of our Cyborgs, we will begin production on the Planet of Cyborgs clothing line, which will feature our original artworks. Revenue from this will be put back into our project for continued development. We will then begin working on Cyborgs in Motion, a set of NFTs that complement the Planet EXCLUSIVE for Cyborg holders.'
    },
    {
        title: 'July 2022',
        image: '4',
        mt: '',
        bridge: 'bridge_2.png',
        header: 'The Cyborgs Club',
        body: 'New club details coming soon'
    },
    {
        title: '2023 Manga',
        image: '5',
        mt: '-4rem',
        bridge: 'bridge_1.png',
        header: 'Manga and Metaverses Expansion',
        body: 'Following the production of our clothing line, we will begin the process of hiring writers and artists to work alongside our Cyborgs artist on our own manga adaptation available FREE to our holders. We will also begin our expansion into metaverses, in which we will be experimenting with devs and collaborating on exciting blockchain features we can use to reward our holders!'
    },
    {
        title: 'Ongoing',
        image: '3',
        mt: '-3rem',
        bridge: '',
        header: 'Features',
        body: 'A percentage of our overall royalties and revenue will be reinvested into the project. We will also be donating a percentage of revenue to a charity voted on by our community.'
    }
  ];